### ISSUE TITLE
new lines in in-line table are not recognized

### ISSUE THREAD

**Issue by jotego** [jasonwilliams/sublime_toml_highlighting#21]
About a year ago, TOML was modified to accept new lines in in-line tables. See [the request ](https://github.com/toml-lang/toml/issues/516 )and [the fix](https://github.com/toml-lang/toml/pull/904).

The syntax highlighting package for Sublime does not recognize this syntax and will mark in red text in an in-line table if a new line is added, such as this:

```
# Single line
person = { name = "Tom", geography = { lat = 1.0, lon = 2.0 } }

# Multi line
person = { 
    name = "Tom", 
    geography = { 
        lat = 1.0, 
        lon = 2.0,
    },
}
```

Could you please add support for it? Thank you

**Comment by Satellile** [comment]
A fix that works at a quick glance is to go in `TOML.sublime-syntax` and replace 

```yaml
  inline-keyval-sep:
    - match: '{{ws}}(=){{ws}}'
      captures:
        1: punctuation.definition.key-value.toml
      set: [inline-table-keyvals, data-types]
    - match: '(?=\w+|.)'
      scope: invalid.illegal.inline-sep.toml
      pop: true
```

with

```yaml
  inline-keyval-sep:
    - include: comments
    - match: '[ \t\n]*(\w+){{ws}}(=){{ws}}'
      captures:
        1: entity.name.tag.toml
        2: punctuation.definition.key-value.toml
      set: [inline-table-keyvals, data-types]
    - match: '{{ws}}(=){{ws}}'
      captures:
        1: punctuation.definition.key-value.toml
      set: [inline-table-keyvals, data-types]
    - match: '{{wsnl}}\}'
      scope: punctuation.definition.inline-table.end.toml
      pop: true
    - match: '(?=\w+|.)'
      scope: invalid.illegal.inline-sep.toml
      pop: true
```

Also, `inline-table-keyvals` should be changed a bit (though I think this is different from this issue) to avoid error syntax highlighting on trailing commas for inlined tables:

```yaml

  inline-table-keyvals:
    - match: '{{ws}}'
    - match: '\}'
      scope: punctuation.definition.inline-table.end.toml
      pop: true
    - match: ','
      scope: punctuation.separator.inline-table.toml
      set:
        - match: '{{ws}}'
        - match: '\}'
          scope: invalid.illegal.table-end.toml
          pop: true
        - match: ''
          set: [inline-keyval-sep, key]
    - match: '(?=\w+|.)'
      scope: invalid.illegal.inline-key.toml
      pop: true
```
should change scope on line 11 to
```yaml

  inline-table-keyvals:
    - match: '{{ws}}'
    - match: '\}'
      scope: punctuation.definition.inline-table.end.toml
      pop: true
    - match: ','
      scope: punctuation.separator.inline-table.toml
      set:
        - match: '{{ws}}'
        - match: '\}'
          scope: punctuation.definition.inline-table.end.toml
          pop: true
        - match: ''
          set: [inline-keyval-sep, key]
    - match: '(?=\w+|.)'
      scope: invalid.illegal.inline-key.toml
      pop: true
```
